version: "3"

services:
  nginx:
    image: registry-asi.10d.ir/ci-test/nginx #tiangolo/nginx-rtmp
    container_name : panel
    ports:
      - "4444:80"
    volumes:
      - ./nginx/storage:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx
      - ./nginx/limits.conf:/etc/security/limits.conf
      - ./nginx/sysctl.conf:/etc/sysctl.conf
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
